/**
 * Sync Codex: root AGENTS.override.md ## packages (generated by mmaappss) section.
 */

import { runSync } from './core/sync-runner.js';

async function main(): Promise<void> {
  const result = await runSync(['codex']);
  if (result.isErr()) {
    console.error(result.error.message);
    process.exit(1);
  }
  process.exit(0);
}

main().catch((err: unknown) => {
  const msg =
    err != null && typeof err === 'object' && 'error' in err
      ? String((err as { error?: unknown }).error ?? err)
      : err instanceof Error
        ? err.message
        : String(err);
  console.error(msg);
  process.exit(1);
});
