/**
 * Runs a single integration test case: clear, inject config, run sync, assert manifest and paths.
 * Used by the harness; can be run standalone for one case.
 */

import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import type { SyncManifest } from '../scripts/common/sync-manifest.js';
import { syncManifest } from '../scripts/common/sync-manifest.js';
import {
  integrationTestCaseRunnerConfig as runnerConfig,
  type RunOneTestCaseOptions,
  type RunOneTestCaseResult,
} from './integration-test-case-runner.config.js';

export type { RunOneTestCaseOptions, RunOneTestCaseResult };

/**
 * Run clear (tsx mmaappss-sync-clear-all.ts), then sync (tsx mmaappss-sync-all.ts), then assert.
 * Writes a stub mmaappss.config.ts that re-exports config from the test case module.
 */
export async function runOneTestCase(
  options: RunOneTestCaseOptions
): Promise<RunOneTestCaseResult> {
  const { name, testCaseTsPath, expectedManifestPath, runClearFirst, repoRoot, scriptsDir } =
    options;
  const errors: string[] = [];
  const manifestPath = path.join(repoRoot, '.mmaappss', 'sync-manifest.json');

  // Relative path from repo root to test case .ts (for import in stub)
  const relativeImport = path.relative(repoRoot, testCaseTsPath).replace(/\\/g, '/');

  const configFilePath = path.join(repoRoot, runnerConfig.CONSTANTS.CONFIG_FILE);
  const configBackupPath = path.join(
    repoRoot,
    runnerConfig.CONSTANTS.CONFIG_FILE + runnerConfig.CONSTANTS.CONFIG_BACKUP_SUFFIX
  );

  const runScript = (scriptName: string): Promise<number> => {
    return new Promise((resolve) => {
      const child = spawn('npx', ['tsx', path.join(scriptsDir, scriptName)], {
        cwd: path.join(scriptsDir, '..'),
        stdio: 'pipe',
        env: { ...process.env, MMAAPPSS_REPO_ROOT: repoRoot },
      });
      child.on('close', (code: number | null) => resolve(code ?? 0));
    });
  };

  if (runClearFirst) {
    // Run clear with a full config (basic) so all agents are torn down; otherwise agents not in this case's config (e.g. testagent) stay in the manifest.
    const clearStubRelative = path
      .relative(repoRoot, path.join(path.dirname(testCaseTsPath), 'basic.ts'))
      .replace(/\\/g, '/');
    const clearStubContent = `// generated by integration test - do not edit\nimport { testCase } from './${clearStubRelative}';\nexport default testCase.config;\n`;
    try {
      if (fs.existsSync(configFilePath)) fs.renameSync(configFilePath, configBackupPath);
      fs.writeFileSync(configFilePath, clearStubContent, 'utf8');
    } catch (e) {
      errors.push(`${name}: failed to write clear stub config: ${(e as Error).message}`);
      if (fs.existsSync(configBackupPath)) fs.renameSync(configBackupPath, configFilePath);
      return { passed: false, errors };
    }
    const clearResult = await runScript('mmaappss-sync-clear-all.ts');
    try {
      if (fs.existsSync(configFilePath)) fs.unlinkSync(configFilePath);
      if (fs.existsSync(configBackupPath)) fs.renameSync(configBackupPath, configFilePath);
    } catch {
      // best effort
    }
    if (clearResult !== 0) {
      errors.push(`${name}: clear script exited with ${clearResult}`);
      return { passed: false, errors };
    }
  }

  // Write stub mmaappss.config.ts (default export = testCase.config for sync loader)
  const stubContent = `// generated by integration test - do not edit\nimport { testCase } from './${relativeImport}';\nexport default testCase.config;\n`;
  try {
    if (fs.existsSync(configFilePath)) {
      fs.renameSync(configFilePath, configBackupPath);
    }
    fs.writeFileSync(configFilePath, stubContent, 'utf8');
  } catch (e) {
    errors.push(`${name}: failed to write stub config: ${(e as Error).message}`);
    if (fs.existsSync(configBackupPath)) fs.renameSync(configBackupPath, configFilePath);
    return { passed: false, errors };
  }

  const syncExitCode = await runScript('mmaappss-sync-all.ts');

  // Restore config
  try {
    if (fs.existsSync(configFilePath)) fs.unlinkSync(configFilePath);
    if (fs.existsSync(configBackupPath)) fs.renameSync(configBackupPath, configFilePath);
  } catch {
    // best effort
  }

  if (syncExitCode !== 0) {
    errors.push(`${name}: sync script exited with ${syncExitCode}`);
    return { passed: false, errors };
  }

  if (!fs.existsSync(expectedManifestPath)) {
    errors.push(`${name}: expected manifest file missing: ${expectedManifestPath}`);
    return { passed: false, errors };
  }
  let expected: SyncManifest;
  try {
    expected = JSON.parse(fs.readFileSync(expectedManifestPath, 'utf8')) as SyncManifest;
  } catch (e) {
    errors.push(`${name}: invalid expected JSON: ${(e as Error).message}`);
    return { passed: false, errors };
  }
  const actual = syncManifest.load(manifestPath);

  const actualAgents = Object.keys(actual).sort();
  const expectedAgents = Object.keys(expected).sort();
  if (
    actualAgents.length !== expectedAgents.length ||
    actualAgents.some((a, i) => a !== expectedAgents[i])
  ) {
    errors.push(
      `${name}: manifest agents mismatch: expected [${expectedAgents.join(', ')}], got [${actualAgents.join(', ')}]`
    );
  } else {
    for (const agent of actualAgents) {
      const aBehaviors = Object.keys(actual[agent] ?? {}).sort();
      const eBehaviors = Object.keys(expected[agent] ?? {}).sort();
      if (
        aBehaviors.length !== eBehaviors.length ||
        aBehaviors.some((b, i) => b !== eBehaviors[i])
      ) {
        errors.push(
          `${name}: manifest behaviors for ${agent} mismatch: expected [${eBehaviors.join(', ')}], got [${aBehaviors.join(', ')}]`
        );
      }
    }
  }

  const pathsToExist = runnerConfig.collectManifestPaths(actual, repoRoot);
  for (const p of pathsToExist) {
    if (!fs.existsSync(p)) {
      errors.push(`${name}: path should exist after sync: ${path.relative(repoRoot, p)}`);
    }
  }

  return {
    passed: errors.length === 0,
    errors,
  };
}
