/**
 * Codex-specific markdown cleanup: section heading constants and legacy orphan block removal.
 * All Codex-specific behavior for AGENTS.override.md lives here; only the preset imports this.
 */

import type { Result } from 'neverthrow';
import { markdownSection } from '../../../common/markdown-section.js';

/** Regex for orphan ### X marketplace blocks (no backticks in heading) from the old format. */
const LEGACY_ORPHAN_BLOCK_START = /^###\s+[^`]+marketplace\s*$/i;

/**
 * Codex preset config: section headings and legacy markdown cleanup.
 * Single exported object for convenience and consistent access.
 */
export const codexAgentPresetConfig = {
  CONSTANTS: {
    /** Runtime agent identifier for codex. */
    AGENT_NAME: 'codex',
    /** Root file updated with generated packages section. */
    AGENTS_OVERRIDE_FILE: 'AGENTS.override.md',
    /** Legacy section heading removed when migrating to new format. */
    CODEX_LEGACY_HEADING: 'Codex Marketplace',
    /** Section heading for the generated packages block (sync adds ##). */
    CODEX_SECTION_HEADING: 'packages (generated by mmaappss)',
    /** Env var that enables/disables codex marketplace sync. */
    ENV_VAR: 'MMAAPPSS_MARKETPLACE_CODEX',
  } as const,

  /** Section heading for the generated packages block in AGENTS.override.md (raw text; sync behavior adds ##). */
  get CODEX_SECTION_HEADING(): string {
    return this.CONSTANTS.CODEX_SECTION_HEADING;
  },
  /** Legacy section heading to remove when migrating to the new format. */
  get CODEX_LEGACY_HEADING(): string {
    return this.CONSTANTS.CODEX_LEGACY_HEADING;
  },

  /**
   * Removes legacy orphan ### X marketplace blocks (no ## parent) from AGENTS.override.md.
   * Uses the generic markdownSection.removeBlocksMatching with Codex-specific pattern.
   */
  removeCodexLegacyOrphanBlocks(filePath: string): Result<void, Error> {
    return markdownSection.removeBlocksMatching(filePath, {
      blockStartLineRegex: LEGACY_ORPHAN_BLOCK_START,
    });
  },
};
