/**
 * Runs a single integration test case: clone sandbox-template to sandbox, clear, sync with output root = sandbox, assert manifest and paths, destroy sandbox.
 */

import { syncManifest } from '@mmaappss/sync/sync-manifest';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import {
  integrationTestCaseRunnerConfig as runnerConfig,
  type RunOneTestCaseOptions,
  type RunOneTestCaseResult,
} from './integration-test-case-runner.config.js';
import { diffManifest } from './utils/diff-manifest.js';
import { fileAssertions } from './utils/file-assertions.js';

export type { RunOneTestCaseOptions, RunOneTestCaseResult };

function runScript(
  scriptName: string,
  env: NodeJS.ProcessEnv,
  scriptsDir: string
): Promise<number> {
  return new Promise((resolve) => {
    const child = spawn('npx', ['tsx', path.join(scriptsDir, scriptName)], {
      cwd: path.join(scriptsDir, '..'),
      stdio: 'pipe',
      env,
    });
    child.on('close', (code: number | null) => resolve(code ?? 0));
  });
}

export async function runOneTestCase(
  options: RunOneTestCaseOptions
): Promise<RunOneTestCaseResult> {
  const {
    name,
    testCaseTsPath,
    expectedManifestPath,
    runClearFirst,
    repoRoot,
    outputRoot,
    scriptsDir,
  } = options;
  const errors: string[] = [];

  if (!fs.existsSync(outputRoot)) {
    fs.mkdirSync(path.dirname(outputRoot), { recursive: true });
  }

  const sandboxTemplate = path.join(path.dirname(outputRoot), 'sandbox-template');
  if (!fs.existsSync(sandboxTemplate)) {
    errors.push(`${name}: sandbox-template missing: ${sandboxTemplate}`);
    return { passed: false, errors };
  }

  const configFilePath = path.join(repoRoot, runnerConfig.CONSTANTS.CONFIG_FILE);
  const configBackupPath = path.join(
    repoRoot,
    runnerConfig.CONSTANTS.CONFIG_FILE + runnerConfig.CONSTANTS.CONFIG_BACKUP_SUFFIX
  );
  const relativeImport = path.relative(repoRoot, testCaseTsPath).replace(/\\/g, '/');

  const env = {
    ...process.env,
    MMAAPPSS_REPO_ROOT: repoRoot,
    MMAAPPSS_OUTPUT_ROOT: outputRoot,
  };

  const cleanupSandbox = (): void => {
    try {
      if (fs.existsSync(outputRoot)) {
        fs.rmSync(outputRoot, { recursive: true });
      }
    } catch {
      // best effort
    }
  };

  const restoreConfig = (): void => {
    try {
      if (fs.existsSync(configFilePath)) fs.unlinkSync(configFilePath);
      if (fs.existsSync(configBackupPath)) fs.renameSync(configBackupPath, configFilePath);
    } catch {
      // best effort
    }
  };

  cleanupSandbox();
  try {
    fs.cpSync(sandboxTemplate, outputRoot, { recursive: true });
  } catch (e) {
    errors.push(`${name}: failed to clone sandbox-template: ${(e as Error).message}`);
    restoreConfig();
    return { passed: false, errors };
  }

  if (runClearFirst) {
    const clearStubRelative = path
      .relative(repoRoot, path.join(path.dirname(testCaseTsPath), 'basic.ts'))
      .replace(/\\/g, '/');
    const clearStubContent = `// generated by integration test\nimport { testCase } from './${clearStubRelative}';\nexport default testCase.config;\n`;
    try {
      if (fs.existsSync(configFilePath)) fs.renameSync(configFilePath, configBackupPath);
      fs.writeFileSync(configFilePath, clearStubContent, 'utf8');
    } catch (e) {
      errors.push(`${name}: failed to write clear stub: ${(e as Error).message}`);
      restoreConfig();
      cleanupSandbox();
      return { passed: false, errors };
    }
    const clearResult = await runScript('mmaappss-sync-clear-all.ts', env, scriptsDir);
    try {
      if (fs.existsSync(configFilePath)) fs.unlinkSync(configFilePath);
      if (fs.existsSync(configBackupPath)) fs.renameSync(configBackupPath, configFilePath);
    } catch {
      // best effort
    }
    if (clearResult !== 0) {
      errors.push(`${name}: clear script exited with ${clearResult}`);
      restoreConfig();
      cleanupSandbox();
      return { passed: false, errors };
    }
  }

  const stubContent = `// generated by integration test\nimport { testCase } from './${relativeImport}';\nexport default testCase.config;\n`;
  try {
    if (fs.existsSync(configFilePath)) fs.renameSync(configFilePath, configBackupPath);
    fs.writeFileSync(configFilePath, stubContent, 'utf8');
  } catch (e) {
    errors.push(`${name}: failed to write stub config: ${(e as Error).message}`);
    restoreConfig();
    cleanupSandbox();
    return { passed: false, errors };
  }

  const syncExitCode = await runScript('mmaappss-sync-all.ts', env, scriptsDir);
  restoreConfig();

  if (syncExitCode !== 0) {
    errors.push(`${name}: sync script exited with ${syncExitCode}`);
    cleanupSandbox();
    return { passed: false, errors };
  }

  const manifestPath = path.join(outputRoot, '.mmaappss', 'sync-manifest.json');
  if (!fs.existsSync(expectedManifestPath)) {
    errors.push(`${name}: expected manifest file missing: ${expectedManifestPath}`);
    cleanupSandbox();
    return { passed: false, errors };
  }

  let expected: Record<string, Record<string, unknown>>;
  try {
    expected = JSON.parse(fs.readFileSync(expectedManifestPath, 'utf8'));
  } catch (e) {
    errors.push(`${name}: invalid expected JSON: ${(e as Error).message}`);
    cleanupSandbox();
    return { passed: false, errors };
  }

  const actual = syncManifest.load(manifestPath) as Record<string, Record<string, unknown>>;
  const diff = diffManifest.runDiff(expected, actual);
  if (diff.added.length > 0 || diff.removed.length > 0 || diff.modified.length > 0) {
    errors.push(`${name}: manifest diff (extra/missing/mismatched)`);
    if (diff.added.length) {
      for (const p of diff.added) errors.push(`   - ${p} (missing value)`);
    }
    if (diff.removed.length) {
      for (const p of diff.removed) errors.push(`   + ${p} (unexpected extra value)`);
    }
    if (diff.modified.length) {
      for (const p of diff.modified) errors.push(`   ~ ${p} (mismatched value)`);
    }
  }

  const manifestRels = fileAssertions.collectManifestRelativePaths(actual);
  const templateRootForAssert = path.join(path.dirname(outputRoot), 'sandbox-template');
  const fileReport = fileAssertions.assertSandboxPaths(outputRoot, manifestRels, {
    templateRoot: fs.existsSync(templateRootForAssert) ? templateRootForAssert : undefined,
    excludeExtraPrefixes: [
      '.claude/settings.json',
      '.claude-plugin',
      '.gitignore',
      '.mmaappss',
      'AGENTS.override.md',
    ],
  });
  if (fileReport.missing.length > 0) {
    for (const p of fileReport.missing) {
      errors.push(`${name}: path should exist: ${p}`);
    }
  }
  if (fileReport.extra.length > 0) {
    for (const p of fileReport.extra) {
      errors.push(`${name}: path not in manifest (extra): ${p}`);
    }
  }

  cleanupSandbox();

  return {
    passed: errors.length === 0,
    errors,
    manifestDiff:
      diff.added.length || diff.removed.length || diff.modified.length
        ? { added: diff.added, removed: diff.removed, modified: diff.modified }
        : undefined,
  };
}
