/**
 * Sync Codex: root AGENTS.override.md ## packages (generated by mmaappss) section.
 */

import { runSync } from './core/sync-runner.js';

async function main(): Promise<void> {
  const result = await runSync(['codex']);
  if (result.isErr()) {
    console.error(result.error.message);
    process.exit(1);
  }
  process.exit(0);
}

main().catch((err: unknown) => {
  let msg: string;
  if (err instanceof Error) {
    msg = err.message;
  } else if (
    err != null &&
    typeof err === 'object' &&
    'error' in err &&
    (err as { error?: unknown }).error !== undefined
  ) {
    msg = String((err as { error: unknown }).error);
  } else {
    try {
      msg = JSON.stringify(err);
    } catch {
      msg = String(err);
    }
  }
  console.error('Unexpected error in mmaappss-marketplaces-codex-sync', msg);
  process.exit(1);
});
