import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { markdownSection } from './markdown-section.js';

describe('markdown-section', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'mmaappss-'));
  });

  afterEach(async () => {
    await fs.promises.rm(tmpDir, { recursive: true, force: true });
  });

  it('adds section when file does not exist', () => {
    const filePath = path.join(tmpDir, 'AGENTS.md');
    const result = markdownSection.replaceOrAddSection(
      filePath,
      'Codex Marketplace',
      '- [foo](./bar)'
    );

    expect(result.isOk()).toBe(true);
    const content = fs.readFileSync(filePath, 'utf8');
    expect(content).toContain('## Codex Marketplace');
    expect(content).toContain('- [foo](./bar)');
  });

  it('replaces existing section', () => {
    const filePath = path.join(tmpDir, 'AGENTS.md');
    fs.writeFileSync(
      filePath,
      [
        '# Project',
        '',
        '## Codex Marketplace',
        '',
        '- [old](./old)',
        '',
        '## Other',
        '',
        'Keep this.',
      ].join('\n')
    );

    const result = markdownSection.replaceOrAddSection(
      filePath,
      'Codex Marketplace',
      '- [new](./new)'
    );
    expect(result.isOk()).toBe(true);

    const content = fs.readFileSync(filePath, 'utf8');
    expect(content).toContain('- [new](./new)');
    expect(content).not.toContain('- [old](./old)');
    expect(content).toContain('## Other');
    expect(content).toContain('Keep this.');
  });

  it('replaces section with ### subsections (idempotent; no append)', () => {
    const filePath = path.join(tmpDir, 'AGENTS.md');
    const sectionContent = [
      '### `packages/sync/.agents/plugins` marketplace',
      '',
      '- [mmaappss](./packages/sync/.agents/plugins/mmaappss-sync)',
    ].join('\n');
    fs.writeFileSync(
      filePath,
      ['## packages (generated by mmaappss)', '', sectionContent].join('\n')
    );

    const result1 = markdownSection.replaceOrAddSection(
      filePath,
      'packages (generated by mmaappss)',
      sectionContent
    );
    const result2 = markdownSection.replaceOrAddSection(
      filePath,
      'packages (generated by mmaappss)',
      sectionContent
    );
    expect(result1.isOk()).toBe(true);
    expect(result2.isOk()).toBe(true);

    const content = fs.readFileSync(filePath, 'utf8');
    const count = (content.match(/### `packages\/sync\/\.agents\/plugins` marketplace/g) ?? [])
      .length;
    expect(count).toBe(1);
  });

  it('removeSection removes section and preserves rest', () => {
    const filePath = path.join(tmpDir, 'AGENTS.md');
    fs.writeFileSync(
      filePath,
      [
        '# Project',
        '',
        '## Codex Marketplace',
        '',
        'content',
        '',
        '## Other',
        '',
        'Keep this.',
      ].join('\n')
    );

    const result = markdownSection.removeSection(filePath, 'Codex Marketplace');
    expect(result.isOk()).toBe(true);

    const content = fs.readFileSync(filePath, 'utf8');
    expect(content).not.toContain('## Codex Marketplace');
    expect(content).not.toContain('content');
    expect(content).toContain('## Other');
    expect(content).toContain('Keep this.');
  });

  it('removeBlocksMatching removes blocks starting with matching line', () => {
    const filePath = path.join(tmpDir, 'AGENTS.md');
    fs.writeFileSync(
      filePath,
      [
        '### packages/sync/.agents/plugins marketplace',
        '',
        '- [mmaappss](./packages/sync/.agents/plugins/mmaappss-sync)',
        '',
        '## packages (generated by mmaappss)',
        '',
        '### `packages/sync/.agents/plugins` marketplace',
        '',
        '- [mmaappss](./packages/sync/.agents/plugins/mmaappss-sync)',
      ].join('\n')
    );

    const result = markdownSection.removeBlocksMatching(filePath, {
      blockStartLineRegex: /^###\s+[^`]+marketplace\s*$/,
    });
    expect(result.isOk()).toBe(true);

    const content = fs.readFileSync(filePath, 'utf8');
    expect(content).not.toContain('### packages/sync/.agents/plugins marketplace');
    expect(content).toContain('## packages (generated by mmaappss)');
    expect(content).toContain('### `packages/sync/.agents/plugins` marketplace');
  });
});
