/**
 * Codex adapter: surgical edit of AGENTS.md ## packages (generated by mmaappss) section.
 * Lists all marketplaces and plugins with markdown links.
 */

import path from 'node:path';
import { markdownSection } from '../common/markdown-section.js';
import type { DiscoveredMarketplace } from '../common/types.js';
import { AgentAdapterBase } from './agent-adapter-base.js';

const CONFIG = {
  agent: 'codex' as const,
  usesMarkdownSection: true,
  agentsFile: 'AGENTS.md',
  sectionHeading: markdownSection.CODEX_SECTION_HEADING.replace(/^#+\s*/, ''),
};

export const codexAdapter = new (class CodexAdapter extends AgentAdapterBase {
  constructor() {
    super(CONFIG);
  }

  protected override beforeSync(
    repoRoot: string,
    _marketplaces: DiscoveredMarketplace[]
  ): import('neverthrow').Result<void, Error> {
    const filePath = path.join(repoRoot, CONFIG.agentsFile!);
    return markdownSection
      .removeSection(filePath, markdownSection.CODEX_LEGACY_HEADING)
      .andThen(() => markdownSection.removeLegacyOrphanCodexBlocks(filePath));
  }

  protected override buildMarkdownSectionContent(marketplaces: DiscoveredMarketplace[]): string {
    const lines: string[] = [];
    for (const m of marketplaces) {
      if (m.plugins.length === 0) continue;
      lines.push(`### \`${m.relativePath}\` marketplace`, '');
      for (const p of m.plugins) {
        lines.push(`- [${p.manifestName ?? p.name}](./${p.relativePath})`);
      }
      lines.push('');
    }
    return lines.join('\n').trim();
  }
})();
