/**
 * Codex adapter: surgical edit of AGENTS.override.md ## packages (generated by mmaappss) section.
 * We sync to AGENTS.override.md (Codex-only) so the hand-edited AGENTS.md stays untouched.
 * See: https://developers.openai.com/codex/guides/agents-md/
 */

import path from 'node:path';
import { markdownSection } from '../common/markdown-section.js';
import type { DiscoveredMarketplace } from '../common/types.js';
import type { AdapterAgentConfig } from './agent-adapter-base.js';
import { AgentAdapterBase } from './agent-adapter-base.js';

/** Codex checks AGENTS.override.md before AGENTS.md per directory; we write only the override. */
const CODEX_AGENTS_FILE = 'AGENTS.override.md';

const CONFIG = {
  agent: 'codex' as const,
  agentsFile: CODEX_AGENTS_FILE,
  sectionHeading: markdownSection.CODEX_SECTION_HEADING.replace(/^#+\s*/, ''),
  usesMarkdownSection: true,
} satisfies AdapterAgentConfig;

export const codexAdapter = new (class CodexAdapter extends AgentAdapterBase {
  constructor() {
    super(CONFIG);
  }

  protected override beforeSync(
    repoRoot: string,
    _marketplaces: DiscoveredMarketplace[]
  ): import('neverthrow').Result<void, Error> {
    const filePath = path.join(repoRoot, CONFIG.agentsFile ?? CODEX_AGENTS_FILE);
    return markdownSection
      .removeSection(filePath, markdownSection.CODEX_LEGACY_HEADING)
      .andThen(() => markdownSection.removeLegacyOrphanCodexBlocks(filePath));
  }

  protected override buildMarkdownSectionContent(marketplaces: DiscoveredMarketplace[]): string {
    const lines: string[] = [];
    for (const m of marketplaces) {
      if (m.plugins.length === 0) continue;
      lines.push(`### \`${m.relativePath}\` marketplace`, '');
      for (const p of m.plugins) {
        lines.push(`- [${p.manifestName ?? p.name}](./${p.relativePath})`);
      }
      lines.push('');
    }
    return lines.join('\n').trim();
  }
})();
